name: Compile Test

on:
  push:
    branches: [ TEST ]
  pull_request:
    branches: [ TEST ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          pkg-config \
          libssl-dev \
          libcurl4-openssl-dev \
          libfribidi-dev \
          libfreetype6-dev \
          libpng-dev \
          libjpeg-dev \
          libglib2.0-dev \
          libass-dev \
          libtool \
          automake \
          autoconf \
          yasm \
          libavcodec-dev \
          libavformat-dev \
          libswscale-dev \
          libavutil-dev

    - name: Compile exteplayer3
      run: |
        make -j$(nproc)
