name: Compile exteplayer3

on:
  push:
    branches: [ TEST ]
  pull_request:
    branches: [ TEST ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          pkg-config \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          libavutil-dev \
          libswresample-dev \
          libasound2-dev \
          libdl-dev \
          libpthread-stubs0-dev

    - name: Compile exteplayer3
      run: |
        SRC_DIR="$PWD"
        gcc $(find . -name "*.c") \
          -D_FILE_OFFSET_BITS=64 \
          -D_LARGEFILE64_SOURCE \
          -D_LARGEFILE_SOURCE \
          -DHAVE_FLV2MPEG4_CONVERTER \
          -I$SRC_DIR/include \
          -I$SRC_DIR/external \
          -I$SRC_DIR/external/flv2mpeg4 \
          -lswscale -ldl -lpthread -lavformat -lavcodec -lavutil -lswresample \
          -o exteplayer3

    - name: Verify build
      run: |
        ls -lh exteplayer3
        ./exteplayer3 --help || echo "Binary built but no help output"
